name: icsd
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  mine:
    git:
      url: https://github.com/fazil-kp/mine.git
      ref: main
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  carousel_slider: ^5.0.0
  url_strategy: ^0.3.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/splash.png"
  background_color: "#FFFFFF"
  theme_color: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/images/splash.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/splash.png"
    icon_size: 48 

  macos:
    generate: true
    image_path: "assets/images/splash.png"