name: icsd
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  mine:
    git:
      url: https://github.com/fazil-kp/mine.git
      ref: main
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  carousel_slider: ^5.0.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    

